sudo: required
services:
    - docker

before_install:
    - docker build -t scranga/multi-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run scranga/multi-client-test npm test -- --coverage

after_success:
    - docker build -t scranga/multi-client ./client
    - docker build -t scranga/multi-nginx ./nginx
    - docker build -t scranga/multi-server ./server
    - docker build -t scranga/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push scranga/multi-client
    - docker push scranga/multi-nginx
    - docker push scranga/multi-server
    - docker push scranga/multi-worker
